### ISSUE TITLE
> 2 alleles for a single sample

### ISSUE THREAD

**Issue by ngarud** [snayfach/MIDAS#42]
Hi Stephen,

If a single sample has >2 alleles at a single site, is there any way to obtain information about all the alleles from MIDAS output? E.g. let's say at a single site in a single sample there are 10 reads with a T, 10 reads with a C, and 5 reads with an A. Can we obtain info about all the nucleotides present or only the major ones (T and C)?

**Comment by snayfach** [comment]
Yes. This info is stored in the output from run_midas.py snps. This feature
was added several months ago, so you may need to update.

Stephen

**Comment by ngarud** [comment]
Thanks. I'm running Midas 1.2.2 (downloaded in mid-November 2016). I cannot find which output file has the info about all 4 allelic states. I noticed in snps_info.txt there's a field "allele_props: pooled frequency of 4 nucleotides", but this isn't what I'm looking for. Instead, I'd like allele frequencies of 4 nucleotides within a single sample.

**Comment by snayfach** [comment]
You're looking at the output from merge_midas.py snps. You need to look at
the output from run_midas.py snps

On Dec 14, 2016 4:15 PM, "Nandita Garud" <notifications@github.com> wrote:

Thanks. I'm running Midas 1.2.2 (downloaded in mid-November 2016). I cannot
find which output file has the info about all 4 allelic states. I noticed
in snps_info.txt there's a field "allele_props: pooled frequency of 4
nucleotides", but this isn't what I'm looking for. Instead, I'd like allele
frequencies of 4 nucleotides within a single sample.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/snayfach/MIDAS/issues/42#issuecomment-267197910>, or mute
the thread

**Comment by ngarud** [comment]
Thank you, I have found the info.
